"""p0 initial

Revision ID: d27a8cccffd9
Revises: 
Create Date: 2026-09-06 00:10:29.668532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = 'd27a8cccffd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_n', sa.Integer(), nullable=True),
    sa.Column('loop_n', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index('ix_events_session_type', 'events', ['session_id', 'type'], unique=False)
    op.create_table('scenario_beats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('morning_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario', 'n')
    )
    op.create_table('scenario_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('initial_suspicion', sa.Integer(), nullable=False),
    sa.Column('initial_trust', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario', 'code')
    )
    op.create_table('scenario_cookies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('text_id', sa.String(length=32), nullable=False),
    sa.Column('cell', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario', 'text_id')
    )
    op.create_table('scenario_truth_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('cell', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario', 'code')
    )
    op.create_table('truth_claim_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('claim_code', sa.String(length=32), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario', 'claim_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truth_claim_embeddings')
    op.drop_table('scenario_truth_claims')
    op.drop_table('scenario_cookies')
    op.drop_table('scenario_characters')
    op.drop_table('scenario_beats')
    op.drop_index('ix_events_session_type', table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
