"""p1-p5 game tables

Revision ID: 9d274ffb88a1
Revises: e5d6c3d3b433
Create Date: 2026-09-06 00:39:48.252829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9d274ffb88a1'
down_revision: Union[str, None] = 'e5d6c3d3b433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_n', sa.Integer(), nullable=False),
    sa.Column('prior_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_by', sa.String(length=20), nullable=True),
    sa.Column('prior_cell_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cookies_seen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('paw_offered_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('loop_n', sa.Integer(), nullable=False),
    sa.Column('beat', sa.Integer(), nullable=False),
    sa.Column('budget_left', sa.Integer(), nullable=False),
    sa.Column('ask_budget_left', sa.Integer(), nullable=False),
    sa.Column('manager_budget_left', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('damage_level', sa.Integer(), nullable=False),
    sa.Column('morning_shifted', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('world_outcome', sa.String(length=16), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('rumor_index', sa.Integer(), nullable=False),
    sa.Column('cause_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('side_effect_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_paw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'loop_n')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('loop_n', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'source_key')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('when_beat', sa.Integer(), nullable=True),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('shown_reason', sa.Text(), nullable=True),
    sa.Column('hidden_side_effect', sa.Text(), nullable=True),
    sa.Column('created_loop', sa.Integer(), nullable=False),
    sa.Column('conflict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'rule_id')
    )
    op.create_table('nights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loop_id', sa.Uuid(), nullable=False),
    sa.Column('tapped_note_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fabricated_dropped', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('per_truth_claim', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cell_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('questions_left', sa.Integer(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rule_chosen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loop_id')
    )
    op.create_table('npc_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loop_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('suspicion', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('opposite_mode', sa.Boolean(), nullable=False),
    sa.Column('flagged_abnormal', sa.Boolean(), nullable=False),
    sa.Column('mood', sa.String(length=16), nullable=False),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loop_id', 'code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('npc_states')
    op.drop_table('nights')
    op.drop_table('rules')
    op.drop_table('notes')
    op.drop_table('loops')
    op.drop_table('attempts')
    # ### end Alembic commands ###
